// <auto-generated />
using System;
using ExpenseTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251230121243_AddInitialData")]
    partial class AddInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Core.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54dc7648-c68d-41c3-97d2-ca0885a9099f"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 12, 30, 18, 5, 47, 0, DateTimeKind.Unspecified), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "Monthly Salary",
                            IsGlobal = true,
                            Name = "Salary",
                            Type = (short)1
                        },
                        new
                        {
                            Id = new Guid("3b39708c-9742-4e42-8c6e-771efacb40ed"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 12, 30, 18, 5, 47, 0, DateTimeKind.Unspecified), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "Freelance Income",
                            IsGlobal = false,
                            Name = "Freelance",
                            Type = (short)1
                        },
                        new
                        {
                            Id = new Guid("ecd4b597-5cd1-4b00-b2a0-ff059f6dec85"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 12, 30, 18, 5, 47, 0, DateTimeKind.Unspecified), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "Food and Dining Expenses",
                            IsGlobal = true,
                            Name = "Food",
                            Type = (short)2
                        },
                        new
                        {
                            Id = new Guid("e4df724c-7e92-40f8-be2c-622aa899298a"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 12, 30, 18, 5, 47, 0, DateTimeKind.Unspecified), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "Monthly House Rent Payment",
                            IsGlobal = true,
                            Name = "House Rent",
                            Type = (short)2
                        },
                        new
                        {
                            Id = new Guid("d564877a-0765-4b9d-bc24-9d228ea267b1"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 12, 30, 18, 5, 47, 0, DateTimeKind.Unspecified), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "Utility Bills like Electricity, Water, Internet",
                            IsGlobal = true,
                            Name = "Utilities",
                            Type = (short)2
                        },
                        new
                        {
                            Id = new Guid("dabbec01-1df9-4d8a-bd6a-9d6fd0e44128"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 12, 30, 18, 5, 47, 0, DateTimeKind.Unspecified), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "Transportation Expenses like Bus, Taxi, Fuel",
                            IsGlobal = true,
                            Name = "Transportation",
                            Type = (short)2
                        },
                        new
                        {
                            Id = new Guid("3ddf5524-7fda-4537-b596-0dad4e6a1867"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 12, 30, 18, 5, 47, 0, DateTimeKind.Unspecified), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "Entertainment Expenses like  Events",
                            IsGlobal = true,
                            Name = "Entertainment",
                            Type = (short)2
                        },
                        new
                        {
                            Id = new Guid("f7129929-faa9-4b47-afd7-b07d6a88566f"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 12, 30, 18, 5, 47, 0, DateTimeKind.Unspecified), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "Medical and Healthcare Expenses",
                            IsGlobal = true,
                            Name = "Healthcare",
                            Type = (short)2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
