<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExpenseTracker.Core.Domain\ExpenseTracker.Core.Domain.csproj" />
    <ProjectReference Include="..\ExpenseTracker.Shared.RequestFeature\ExpenseTracker.Shared.RequestFeature.csproj" />
  </ItemGroup>

</Project>
